// extracted and reduced data for development
const credits = [
    {
        cast: [{'character': 'Woody (voice)', 'id': 31, 'name': 'Tom Hanks', 'order': 0}, {'character': 'Buzz Lightyear (voice)', 'id': 12898, 'name': 'Tim Allen', 'order': 1}, {'character': 'Mr. Potato Head (voice)', 'id': 7167, 'name': 'Don Rickles', 'order': 2}, {'character': 'Slinky Dog (voice)', 'id': 12899, 'name': 'Jim Varney', 'order': 3}, {'character': 'Rex (voice)', 'id': 12900, 'name': 'Wallace Shawn', 'order': 4}, {'character': 'Hamm (voice)', 'id': 7907, 'name': 'John Ratzenberger', 'order': 5}, {'character': 'Bo Peep (voice)', 'id': 8873, 'name': 'Annie Potts', 'order': 6}, {'character': 'Andy (voice)', 'id': 1116442, 'name': 'John Morris', 'order': 7}, {'character': 'Sid (voice)', 'id': 12901, 'name': 'Erik von Detten', 'order': 8}, {'character': 'Mrs. Davis (voice)', 'id': 12133, 'name': 'Laurie Metcalf', 'order': 9}, {'character': 'Sergeant (voice)', 'id': 8655, 'name': 'R. Lee Ermey', 'order': 10}, {'character': 'Hannah (voice)', 'id': 12903, 'name': 'Sarah Freeman', 'order': 11}, {'character': 'TV Announcer (voice)', 'id': 37221, 'name': 'Penn Jillette', 'order': 12}],
        id: 862,
    },
    {
        cast: [{'character': 'Jericho Cane', 'id': 1100, 'name': 'Arnold Schwarzenegger', 'order': 0}, {'character': 'Satan', 'id': 5168, 'name': 'Gabriel Byrne', 'order': 1}, {'character': 'Bobby Chicago', 'id': 7166, 'name': 'Kevin Pollak', 'order': 2}, {'character': 'Christine York', 'id': 17346, 'name': 'Robin Tunney', 'order': 3}, {'character': 'Detective Margie Francis', 'id': 30485, 'name': 'CCH Pounder', 'order': 4}, {'character': 'Father Kovak', 'id': 522, 'name': 'Rod Steiger', 'order': 5}, {'character': 'Thomas Aquinas', 'id': 14325, 'name': "Derrick O'Connor", 'order': 6}, {'character': 'Mabel', 'id': 6199, 'name': 'Miriam Margolyes', 'order': 7}, {'character': 'Head Priest', 'id': 1646, 'name': 'Udo Kier', 'order': 8}, {'character': 'Pope', 'id': 1173, 'name': 'Mark Margolis', 'order': 9}, {'character': 'Skateboarder', 'id': 1570367, 'name': 'Jonny Bogris', 'order': 10}, {'character': 'Albino', 'id': 215304, 'name': 'Victor Varnado', 'order': 11}, {'character': 'Cardinal', 'id': 53490, 'name': "Michael O'Hagan", 'order': 12}],
        id: 9946,
    },
    {
        cast: [{'character': 'Woody (voice)', 'id': 31, 'name': 'Tom Hanks', 'order': 0}, {'character': 'Buzz Lightyear (voice)', 'id': 12898, 'name': 'Tim Allen', 'order': 1}, {'character': 'Jessie (voice)', 'id': 3234, 'name': 'Joan Cusack', 'order': 2}, {'character': 'Prospector (voice)', 'id': 7090, 'name': 'Kelsey Grammer', 'order': 3}, {'character': 'Mr. Potato Head (voice)', 'id': 7167, 'name': 'Don Rickles', 'order': 4}, {'character': 'Slinky Dog (voice)', 'id': 12899, 'name': 'Jim Varney', 'order': 5}, {'character': 'Rex (voice)', 'id': 12900, 'name': 'Wallace Shawn', 'order': 6}, {'character': 'Hamm (voice)', 'id': 7907, 'name': 'John Ratzenberger', 'order': 7}, {'character': 'Bo Peep (voice)', 'id': 8873, 'name': 'Annie Potts', 'order': 8}, {'character': 'Al McWhiggin (voice)', 'id': 4201, 'name': 'Wayne Knight', 'order': 9}, {'character': 'Andy (voice)', 'id': 1116442, 'name': 'John Morris', 'order': 10}, {'character': "Andy's Mom (voice)", 'id': 12133, 'name': 'Laurie Metcalf', 'order': 11}, {'character': 'Mrs. Potato Head (voice)', 'id': 61964, 'name': 'Estelle Harris', 'order': 12}, {'character': 'Sarge (voice)', 'id': 8655, 'name': 'R. Lee Ermey', 'order': 13}, {'character': 'Barbie (voice)', 'id': 63978, 'name': 'Jodi Benson', 'order': 14}, {'character': 'The Cleaner (voice)', 'id': 123037, 'name': 'Jonathan Harris', 'order': 15}, {'character': 'Wheezy (voice)', 'id': 7911, 'name': 'Joe Ranft', 'order': 16}, {'character': 'Emperor Zurg (voice)', 'id': 7, 'name': 'Andrew Stanton', 'order': 17}, {'character': 'Aliens (voice)', 'id': 7882, 'name': 'Jeff Pidgeon', 'order': 18}, {'character': "Woody's Roundup Announcer (voice)", 'id': 35219, 'name': 'Corey Burton', 'order': 19}, {'character': "Blue Rock 'Em Sock 'Em Robot (voice)", 'id': 7879, 'name': 'John Lasseter', 'order': 20}, {'character': 'Mom at yard sale (voice)', 'id': 84493, 'name': 'Mickie McGowan', 'order': 21}, {'character': 'Airline Rep / sign-off voice / Mr. Konishi (voice)', 'id': 61969, 'name': 'Phil Proctor', 'order': 22}, {'character': "Red Rock 'Em Sock 'Em Robot (voice)", 'id': 8, 'name': 'Lee Unkrich', 'order': 23}],
        id: 863,
    }
];

export default credits;